### ISSUE TITLE
Plans on Python 3.7 support

### ISSUE THREAD

**Issue by kmaehashi** [intel/ideep#25]
As more and more users started using Python 3.7.x, it is nice if you provide Python 3.7 wheels.
https://pypi.org/project/ideep4py/2.0.0.post3/#files

Thanks in advance!

**Comment by mingxiaoh** [comment]
@kmaehashi We can successfully build ideep4py on python3.7 now, full test is on-going now, and test is so far so good. We will provide python3.7 wheel once full test pass, it should be done in one or two days.

**Comment by kmaehashi** [comment]
@mingxiaoh Thank you for your prompt action!

**Comment by kmaehashi** [comment]
Thank you!

**Comment by kmaehashi** [comment]
It seems Python 3.7 wheel requires NumPy 1.16. Is this intended?

On Python 3.7 + `ideep4py==2.0.0.post3` + `numpy==1.15.4`:

```
>>> import ideep4py
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kenichi/.pyenv/versions/local-3.7.0/lib/python3.7/site-packages/ideep4py/__init__.py", line 4, in <module>
    from ideep4py._ideep4py import intVector  # NOQA
ImportError: numpy.core.multiarray failed to import
```

There's no problem with the following configuration:

* Python 3.7 + `ideep4py==2.0.0.post3` + `numpy==1.16.0`
* Python 3.6 + `ideep4py==2.0.0.post3` + `numpy==1.15.4`

**Comment by mingxiaoh** [comment]
@kmaehashi We first try to use numpy=1.13, which, however, is not compatible with python3.7. So, we made the Python 3.7 wheel based on numpy==1.16.0 on our environment.  Do you need a  Python 3.7 wheel  with specific numpy ==1.15.4?

**Comment by kmaehashi** [comment]
@mingxiaoh Thanks for clarification.
Currently, we don't have specific use-case for Python 3.7 with NumPy 1.15.4 (or earlier). However I think it's nice if such requirements are documented in README. It is almost impossible for users to guess why the above error message appears.

**Comment by mingxiaoh** [comment]
@kmaehashi Thanks for suggestion, we just documented this info in README moments ago. Thanks.
